# This compiles the example(s) and the library
from init_env import init_environment
import os

# load needed environment for this library
env = init_environment('glibrary clhep geant4 ccdb')

# standard pre and suffix for gemc plugins and path
env.Replace(SHLIBSUFFIX = ".gplugin")
env.Replace(SHLIBPREFIX = "")
plugins_dir_s   = os.environ.get('GPLUGIN_PATH')
plugins_dir     = os.path.realpath(plugins_dir_s)

env.Append(CXXFLAGS=['-std=c++20'])

sources = [
			  'readoutSpecs.cc',
			  'loadConstants.cc',
			  'loadTT.cc',
			  'hitDigitization.cc'
			  ]















plugin  = env.SharedLibrary( source = sources,  target = 'ftof')



# use scons install to copy the plugin to the plugin directory
# see scons user guide (scons install) for more info
env.Alias('install', plugins_dir)
env.Install(plugins_dir, plugin)