# This compiles the example(s) and the library
from init_env import init_environment

# load needed environment for this library
env = init_environment('glibrary clhep geant4 ccdb')
env.Append(CXXFLAGS=['-std=c++17'])


# standard pre and suffix for gemc plugins
env.Replace(SHLIBSUFFIX = ".gplugin")
env.Replace(SHLIBPREFIX = "")

sources = [
			  'readoutSpecs.cc',
			  'loadConstants.cc',
			  'loadTT.cc',
			  'hitDigitization.cc'
			  ]

plugin  = env.SharedLibrary( source = sources,  target = 'ftof')

