# This compiles the example(s) and the library
from init_env import init_environment

# load needed environment for this library
env = init_environment('glibrary clhep geant4 ccdb')
env.Append(CXXFLAGS=['-std=c++17'])


# standard pre and suffix for gemc plugins
env.Replace(SHLIBSUFFIX = ".gplugin")
env.Replace(SHLIBPREFIX = "")

ft_cal_sources = [
			  'ft_cal_readoutSpecs.cc',
			  'ft_cal_loadConstants.cc',
			  'ft_cal_loadTT.cc',
			  'ft_cal_hitDigitization.cc'
			  ]

ft_hodo_sources = [
			  'ft_hodo_readoutSpecs.cc',
			  'ft_hodo_loadConstants.cc',
			  'ft_hodo_loadTT.cc',
			  'ft_hodo_hitDigitization.cc'
			  ]

ft_mmtrk_sources = [
			  'ft_mmtrk_readoutSpecs.cc',
			  'ft_mmtrk_loadConstants.cc',
			  'ft_mmtrk_stripSharing.cc',
			  'ft_mmtrk_hitDigitization.cc'
			  ]

ft_cal_plugin   = env.SharedLibrary( source = ft_cal_sources,   target = 'ft_cal')
ft_hodo_plugin  = env.SharedLibrary( source = ft_hodo_sources,  target = 'ft_hodo')
ft_mmtrk_plugin = env.SharedLibrary( source = ft_mmtrk_sources, target = 'ft_mmtrk')

