name: Dawn Screenshot

# Controls when the workflow will run
on:
  # Triggers the workflow on all pushes
  push:
  pull_request:
    types:
      # only run workflow when a commit is pushed to a PR branch
      # instead of running for all other PR events
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix:  ${{ steps.set-matrix.outputs.matrix }}
      jobtype: ${{ steps.set-matrix.outputs.jobtype }}
    steps:
      - name: Check changed files
        uses: actions/checkout@main
      - id: set-matrix
        run: |
          if [ $GITHUB_BASE_REF ]; then
            BASE_REF=no
          else
            BASE_REF=$GITHUB_BASE_REF
          fi
          export JSON=$(    ./ci/whatToTest.sh -b $BASE_REF -c $GITHUB_SHA -g $GITHUB_BEFORE )
          export JOBTYPE=$( echo $JSON | grep irrelevant | wc -l )
          echo generate-matrix: $JSON, ignore:  $JOBTYPE
          echo "::set-output name=matrix::$(  echo "$JSON"    | tr -d '\n' )"
          echo "::set-output name=jobtype::$( echo "$JOBTYPE" | tr -d '\n' )"
    env:
      GITHUB_BEFORE: ${{ github.event.before }}


  # Run jcard in tests directory
  runTests:
    needs: generate-matrix
    if: needs.generate-matrix.outputs.jobtype == '0'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: jeffersonlab/clas12-systems:dev-fedora36
    name: Dawn Screenshot ${{ matrix.detector }}
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Run Dawn
        run: |
          ./ci/tests.sh -s ${{ matrix.detector }} -d

      # https://github.com/stefanzweifel/git-auto-commit-action
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes
          file_pattern: 'screenshots/*/*.pdf'
      - uses: gitboard-io/gitboard-action@main
        with:
          username: maureeungaro
          key: 3d8e9059-a164-4bea-9541-1cb8789d805b

